server:
  port: ${PORT:8081}

security:
  basic:
    enabled: false

management:
  security:
    enabled: false

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/strijkatelier
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: validate
      format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        jdbc.lob.non_contextual_creation: true
  mail:
    host:
    port: 465
    protocol: smtps
    username: admin@strijkatelier.be
    password: password
    properties:
      mail:
        smtp:
          timeout: 8000
          auth: true
          starttls:
            enable: false
      protocol: smtp
      test-connection: false

logging:
  level:
    org.hibernate.SQL: DEBUG

support:
  email: USERNAME@gmail.com

api:
  security:
    enabled: true
    jwt:
      secret: jwt_secret
      validity: 180000