server:
  port: ${PORT:8081}

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost/strijkatelier
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        jdbc.lob.non_contextual_creation: true
  mail:
    host: smtp.gmail.com
    port: 465
    protocol: smtps
    username: USERNAME@gmail.com
    password: PASSWORD
    properties:
      mail:
        smtp:
          timeout: 8000
          auth: true
          starttls:
            enable: true
      protocol: smtp
      test-connection: false

logging:
  level:
    org.hibernate.SQL: DEBUG

support:
  email: USERNAME@gmail.com

google:
  recaptcha:
    key:
      site: 6LfaHiITAAAAAAgZBHl4ZUZAYk5RlOYTr6m2N34X
      secret: 6LfaHiITAAAAANpDTA_Zflwib95IhDqg2SNRLt4U
purge:
  cron:
    expression: 0 0 5 * * ?